### ISSUE TITLE
Python 3 support? Getting error

### ISSUE THREAD

**Issue by Logmytech** [jvanasco/metadata_parser#11]
I'm getting `TypeError: cannot use a string pattern on a bytes-like object`

```
/home/user/myProject/venv/lib/python3.5/site-packages/metadata_parser/__init__.py:947: FutureWarning: `search_head_only` was not provided and defaulting to `True` Future versions will default to `False`.
  warn_future("""`search_head_only` was not provided and defaulting to `True` """
Traceback (most recent call last):
  File "metadata.py", line 3, in <module>
    page = metadata_parser.MetadataParser(url="http://www.example.com")
  File "/home/user/myProject/venv/lib/python3.5/site-packages/metadata_parser/__init__.py", line 969, in __init__
    url_headers=url_headers,
  File "/home/user/myProject/venv/lib/python3.5/site-packages/metadata_parser/__init__.py", line 1092, in fetch_url
    timeout=requests_timeout, stream=True,
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/user/myProject/venv/lib/python3.5/site-packages/metadata_parser/__init__.py", line 299, in derive_encoding__hook
    resp._encoding_content = get_encodings_from_content(resp.content[:1024])
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/utils.py", line 406, in get_encodings_from_content
    pragma_re.findall(content) +
TypeError: cannot use a string pattern on a bytes-like object
(venv) student@Windows-PC:~/myProject/scrape$ 
(venv) student@Windows-PC:~/myProject/scrape$ python metadata.py 
/home/user/myProject/venv/lib/python3.5/site-packages/metadata_parser/__init__.py:947: FutureWarning: `search_head_only` was not provided and defaulting to `True` Future versions will default to `False`.
  warn_future("""`search_head_only` was not provided and defaulting to `True` """
Traceback (most recent call last):
  File "metadata.py", line 3, in <module>
    page = metadata_parser.MetadataParser(url="http://www.example.com")
  File "/home/user/myProject/venv/lib/python3.5/site-packages/metadata_parser/__init__.py", line 969, in __init__
    url_headers=url_headers,
  File "/home/user/myProject/venv/lib/python3.5/site-packages/metadata_parser/__init__.py", line 1092, in fetch_url
    timeout=requests_timeout, stream=True,
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/user/myProject/venv/lib/python3.5/site-packages/metadata_parser/__init__.py", line 299, in derive_encoding__hook
    resp._encoding_content = get_encodings_from_content(resp.content[:1024])
  File "/home/user/myProject/venv/lib/python3.5/site-packages/requests/utils.py", line 406, in get_encodings_from_content
    pragma_re.findall(content) +
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by jvanasco** [comment]
Thanks for reporting this. I never ran the testsuite on Python3 after the last updates; it's been fixed in v0.9.15
